### ISSUE TITLE
Cannot parse Experimental Factor Ontology (EFO) in either OBO or OWL format

### ISSUE THREAD

**Issue by fnigsch** [althonos/pronto#101]
pronto 2.3.1 is unable to parse freshly downloaded versions of the EFO in either of OWL or OBO format.

How to reproduce: download EFO (https://www.ebi.ac.uk/efo/) and efo = pronto.Ontology("efo.owl").

Error from OWL format: KeyError: 'RO:0002161'
Error from OBO format: SyntaxError: expected EOL or QuotedString

I would have expected that some of these standard ontologies would work.

**Comment by althonos** [comment]
Hi @fnigsch ,

The OBO file cannot be parsed because it is not a valid OBO format version 1.4 file. This is due to EFO importing ChEBI, [which is also not completely valid either](https://github.com/ebi-chebi/ChEBI/issues/3867).

Concerning the OWL file, this is most likely a bug, I will try to fix the RDF/XML parser.

**Comment by davmlaw** [comment]
Get the same KeyError in Human phenotype ontology hp.owl

Works when I downgrade to Pronto v2.2

**Comment by althonos** [comment]
OWL versions of EFO and HP parse sucessfully in `v2.4.1`. OBO version of EFO is not in valid format, so `pronto` won't be able to parse it unless the EFO developers fix the issues on their end.
