### ISSUE TITLE
Definition string contains cross-references

### ISSUE THREAD

**Issue by pplettner** [althonos/pronto#13]
Hi again,

I'm importing the OBO file from NCIT, and when I extract the definition, I get the whole string unprocessed (i.e. entry.desc contains everything after the quotes). Here's an example entry:

```
[Term]
id: NCIT:C72909
name: Pentopril
def: "A non-sulfhydryl angiotensin converting enzyme (ACE) inhibitor with antihypertensive activity. As a prodrug, pentopril is hydrolyzed into its active form pentoprilat, which competitively inhibits ACE, thereby blocking the conversion of angiotensin I to angiotensin II. This prevents the potent vasoconstrictive actions of angiotensin II and results in vasodilation. Pentoprilat also decreases angiotensin II-induced aldosterone secretion by the adrenal cortex, which leads to an increase in sodium excretion and subsequently increases water outflow." [] {http://purl.obolibrary.org/obo/NCIT_P378="NCI"}
```

So according to the spec (https://owlcollab.github.io/oboformat/doc/GO.format.obo-1_4.html#S.2.2), a "def" entry can consist of a string and a dbxref term. This is done correctly for the synonyms, could you do it for the definition as well?

**Comment by althonos** [comment]
Thanks for raising this issue.
It's done right with synonyms since I made them a proper class, whereas descriptions are still plain strings.

The thing I could do to solve this would be to create a `Description` class with an additional dbxref attribute. How does that sound to you ?

I may be able to solve this as well as #12 in the next few dans, providing I have enough time on my hands and solving these doesn't open a Pandora box.

**Comment by pplettner** [comment]
I think having a ```Description``` class done similarly to the synonyms make sense. Hopefully fixing the OWL parser won't cause too much trouble, because there is another improvement that I might bring up with the OWL properties (again, not a high priority but would be nice to fix)

**Comment by althonos** [comment]
@pplettner : Sorry for the time it took, but it will be fixed in the next release.

I created a `Description` class that inherits from `unicode` in Python 2 and `str` in Python 3, that has the following behaviour:
```python
>>> from pronto.description import Description
>>> d = Description.from_obo('"An awesome description" [SOME:THING, FOO:BAR]')
>>> print(d)
An awesome description
>>> str(d)
"An awesome description"
>>> d.xrefs
['SOME:THING', 'FOO:BAR']
```
so the `d` object should behave more or less like a string (except it has a nicer `repr`, and a `xrefs` attribute).

**Comment by pplettner** [comment]
Thanks @althonos, and no problem about the delay. It's a great package and I'm glad that you're still able to maintain it.
