### ISSUE TITLE
Documentation is missing `term.relationships` attribute

### ISSUE THREAD

**Issue by mukund109** [althonos/pronto#145]
Hey! thanks a lot for developing this library, its been very useful.

Wanted to point out that `term.relationships` isn't documented [here](https://pronto.readthedocs.io/en/v2.4.2/api/pronto.Term.html#pronto.Term). Is that intentional? If so what's the right way to access the relationships for a term?

**Comment by althonos** [comment]
Hi, glad it can be of use to you! That's not intentional, I probably forgot to add back the docstring when I replaced the immutable dictionary with a mutable type in `v2.3.0`. I have added a short docstring with an example: https://pronto.readthedocs.io/en/latest/api/pronto.Term.html#pronto.Term.relationships
