### ISSUE TITLE
pronto==0.4.0 fails when printing obo

### ISSUE THREAD

**Issue by winni-genp** [althonos/pronto#5]
Using the `test.obo`
```
[Term]
id: ONT0:CHILD_0
name: child_0
is_a: ONT0:ROOT ! root

[Term]
id: ONT0:CHILD_1
name: child_1
is_a: ONT0:ROOT ! root

[Term]
id: ONT0:CHILD_2
name: child_2
is_a: ONT0:ROOT ! root

[Term]
id: ONT0:ROOT
name: root
```

when I run the the following python script with pronto 0.4.0:
```
import pronto

for i in xrange(100):
    assert(len(pronto.Ontology("./test.obo")) == 4)

obo = pronto.Ontology("./test.obo")
print(obo.obo)
```

I get the error message
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(obo.obo)
  File "/local/scratch/winni/EchiDNA/phos_env/lib/python2.7/site-packages/pronto/ontology.py", line 129, in obo
    return "\n\n".join( [self._obo_meta()] + [t.obo for t in self if t.id.startswith(self.meta['namespace'][0])])
  File "/local/scratch/winni/EchiDNA/phos_env/lib/python2.7/site-packages/pronto/ontology.py", line 163, in _obo_meta
    ] if "ontology" in self.meta else ["ontology: {}".format(self.meta["namespace"][0].lower())]
KeyError: 'namespace'
```

I'm surprised there isn't an acceptance test for this?

**Comment by althonos** [comment]
I wrote a fix, I'll push it soon.
As for tests, i relied on doctests alone for a time, but I thought I had an
example in a docstring somewhere, which I actually removed.

Current export methods are here for convenience actually, I'll write a
proper Serializer virtual class and at least the Obo Serializer before
v1.0.0 gets released (and some tests as well :p)

Le 20 sept. 2016 11:38 AM, "winni-genp" <notifications@github.com> a écrit :

Using the test.obo

[Term]
id: ONT0:CHILD_0
name: child_0
is_a: ONT0:ROOT ! root

[Term]
id: ONT0:CHILD_1
name: child_1
is_a: ONT0:ROOT ! root

[Term]
id: ONT0:CHILD_2
name: child_2
is_a: ONT0:ROOT ! root

[Term]
id: ONT0:ROOT
name: root

when I run the the following python script with pronto 0.4.0:

import pronto

for i in xrange(100):
    assert(len(pronto.Ontology("./test.obo")) == 4)

obo = pronto.Ontology("./test.obo")
print(obo.obo)

I get the error message

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(obo.obo)
  File "/local/scratch/winni/EchiDNA/phos_env/lib/python2.7/site-packages/pronto/ontology.py",
line 129, in obo
    return "\n\n".join( [self._obo_meta()] + [t.obo for t in self if
t.id.startswith(self.meta['namespace'][0])])
  File "/local/scratch/winni/EchiDNA/phos_env/lib/python2.7/site-packages/pronto/ontology.py",
line 163, in _obo_meta
    ] if "ontology" in self.meta else ["ontology:
{}".format(self.meta["namespace"][0].lower())]
KeyError: 'namespace'

I'm surprised there isn't an acceptance test for this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/althonos/pronto/issues/5>, or mute the thread

**Comment by winni-genp** [comment]
Cheers 👍
