### ISSUE TITLE
Issues with the new Pronto API

### ISSUE THREAD

**Issue by Melnorme1984** [althonos/pronto#55]
I've been upgrading some of my Python 2 code to Python 3 and just noticed today that you completely overhauled Pronto in October.

Unfortunately it seems to have made things more complex for me. I had some nice simple code that did this:

```
def get_psimi_terms():
    psimi_root = read_psimi()[ROOT_DETMETHOD_ID]
    psimi_terms = [psimi_root]
    current_terms = psimi_root.children

    while current_terms:
        psimi_terms.extend(current_terms)
        current_terms = current_terms.children

    return psimi_terms
```

I see that you've got a subclasses iterator that grabs all of a term's descendants, but that's not quite what I need (the fact that some terms might repeat themselves here is intended). And elsewhere in the code I also need to grab each term's immediate parent. Just the parent, not every ancestor. Is there a nice way to implement this now without having to wrestle with the new API?

Another thing (and maybe I should have mentioned this first) is that I'm no longer able to even load the OBO files I was previously using. I'm working with the PSI-MI.OBO from here: https://github.com/HUPO-PSI/psi-mi-CV/blob/master/psi-mi.obo

When I try to load that, I get a `SyntaxError: expected QuotedString` exception from some random term near the end. I also tried GO.OBO and had the same problem. According to your compatibility chart these files are supposed to work, so I'm not sure what's going on here. I didn't have time to investigate this deeply before leaving work today so maybe it's something dumb, but perhaps you can help me.

**Comment by althonos** [comment]
Hi @Melnorme1984 

`pronto` was overhauled recently in order to be more accurate with respect to the OBO format 1.4, where before I was basically interpreting what I thought of an ontology myself with little respects for the semantics.

>  I'm no longer able to even load the OBO files I was previously using

I checked the files, and both of them contain invalid database cross-references identifiers. I'm opening an issue on each of their issue trackers.

As a temporary workaround you can use the 
[psi-mi.obo](https://github.com/althonos/pronto/files/4132795/psi-mi.obo.zip) file I patched that should parse just fine.



> I also need to grab each term's immediate parent

This is actually easy to do since you have that information stored in the `relationships` attribute of each term:
```python
>>> mi = pronto.Ontology("psi-mi.obo")
>>> is_a = mi.get_relationship("is_a")

>>> mi['MI:1002']
Term('MI:1002', name='myristoylase assay')

>>> mi['MI:1002'].relationships['is_a']
frozenset({Term('MI:1001', name='lipidase assay')})
```

> I see that you've got a subclasses iterator that grabs all of a term's descendants, but that's not quite what I need (the fact that some terms might repeat themselves here is intended).

Actually, both the `superclasses` and `subclasses` iterators take a `distance` kwarg that can limit the distance between a term and its parents/children, giving you with a bit of extra elbow-grease what you had earlier:

```python
def get_psimi_terms():
    psimi_root = read_psimi()[ROOT_DETMETHOD_ID]
    psimi_terms = [psimi_root]
    current_terms = list(psimi_root.subclasses(distance=1))[1:]

    while current_terms:
        psimi_terms.extend(current_terms)
        current_terms = [ 
            sub 
            for term in current_terms 
            for sub in  term.subclasses(distance=1)
            if sub != term
        ]

    return psimi_terms
```


Note that `superclasses` and `subclasses` with **always** yield the term itself, as the OBO semantics (with respect to the RDF semantics of `isSubclassOf`) specifies that all terms are subclasses of themselves.  However they will always return the term itself first, so you can simply skip the first item yielded by the iterator (as I did in `list(psimi_root.subclasses(distance=1))[1:]`).

Hope this answers your questions!

**Comment by Melnorme1984** [comment]
Martin, I fear you've set standards here that the academics who maintain these ontologies will never be able to consistently maintain. It would be good if your parser was robust enough to attempt to work with non-standards conforming files.

My project is frequently updated so I don't want to rely on ad-hoc manual fixes. I'll probably just go back to the old version for now, or use another library.

**Comment by althonos** [comment]
> Martin, I fear you've set standards here that the academics who maintain these ontologies will never be able to consistently maintain.

On the contrary, I developed this library with people from the Gene Ontology Consortium as a part of my MSc Thesis, partly in order to fix the mess of the biomedical ontologies world. Raising the strictness bar has led to identification of many issues in numerous ontologies of the OBO Foundry, and their developers have been understanding and reactive about them. This includes developers of the PSI-MI, who only took 3 days to fix the previous issues, so hopefully this will be the case this time as well.

> It would be good if your parser was robust enough to attempt to work with non-standards conforming files.

Again, this is not a robustness issue, this is a strictness issue: the OWL-API, which has become a standard in place of the actual OBO standard, has a lot of leeway in how it deals with the OBO semantics. Because of this, it has made debugging the conversion of ontologies outside of OBO quite hard. The spaces in database cross-references that prevented you from parsing the OBO files are a hard error because they would break during the OBO to OWL conversion and become nonsensical.

**Comment by Melnorme1984** [comment]
I'm sure they'll fix them, but as you see that doesn't mean they'll stay fixed. But hey,  good luck to you. 

I've dropped down to the old Pronto for now. If the OBOs do get fixed and stay fixed,  I would consider updating. It'd be great if you could bring back some of the old functionalities though,  just as syntactic sugar.  For example,  the TermLists where you can get the children or ids for a bunch of terms at once - that was a real selling point of Pronto and the reason I ultimately decided not to use another library.

**Comment by althonos** [comment]
No problem, as long as it works for you it's fine by me! I'll consider adding back the syntactic sugar when I have time, but since I just recently started my PhD I have some other stuff to do in priority before I can get my head around this.

**Comment by althonos** [comment]
@Melnorme1984 : just a heads-up, the `psi-mi.obo` file was fixed upstream.

**Comment by Melnorme1984** [comment]
OK. By the way, here's an example of a cool thing I was able to do with one line of code in the old version using its rchildren().id functionality:

`lca = {descendants: term.id for term in psimi_terms for descendants in itertools.permutations([term.id, term.id, None] + term.rchildren().id, 2)}`

This brute-force generates a dictionary where the key is any tuple of terms in the ontology and the value is their lowest common ancestor. It works because the terms in `psimi_terms` are sorted in order of depth, as seen in my earlier comment.

**Comment by althonos** [comment]
I'm adding the shortcut back in the `v1.2.0` that I'll release today, notably `term.rchildren().id` is now `term.subclasses(with_self=False).to_set().id`. The extra steps here are that 1. you explicitly disable the RDF semantics by not making a term a subclass of itself, and 2. that you want to collect the results in a set as the method now gives you an iterator.

**Comment by Melnorme1984** [comment]
That sounds good. Will you also upload it to Anaconda? Pronto hasn't been updated there since the old version. (It's why it took me a while to notice you'd changed it)

**Comment by Melnorme1984** [comment]
Can you add the `subclasses()` method to the `TermSet` class so it could work like the old `children` property? I think that's all that is missing now.

**Comment by althonos** [comment]
@Melnorme1984 : `TermSet` now have a `subclasses` and `superclasses` method that yields an iterator over all subclasses/superclasses of its members, without duplicates.
