### ISSUE TITLE
error parsing EFO obo file

### ISSUE THREAD

**Issue by diekhans** [althonos/pronto#65]
Parsing http://www.ebi.ac.uk/efo/efo.obo, results in the error:

```
File "../ontologies/efo.obo", line 953
    xref: KEGG COMPOUND:70458-96-7 "CAS Registry Number"␊
               ^
SyntaxError: expected EOL or QuotedString
```

Also, note that http://www.ebi.ac.uk/efo/efo.owl results in a larger number of warnings.

**Comment by althonos** [comment]
This is expected: `pronto` expects OBO 1.4 input, and this `xref` clause is invalid with respect to the [OBO format version 1.4 syntax](http://owlcollab.github.io/oboformat/doc/obo-syntax.html).

Note that the issue comes from a CHEBI imported term, and should have fixed its syntax issues by now, so you may want to report this to the EFO developers. Only regenerating their release file with updated import should fix the issue.

**Comment by diekhans** [comment]
Thanks!

**Comment by diekhans** [comment]
Although it appears that OBO is stuck in working draft for eight years

:-(

**Comment by althonos** [comment]
I did a lot of work on the draft in 2019 to try to get it closer to OWL semantics, but it's hard enforcing a standard on the community that is expecting stuff to *just work* as long as the OWL-API supports it. That's why I try to enforce the spec with the [`fastobo`](https://github.com/fastobo/) stack :smiley:

**Comment by diekhans** [comment]
Genomics is even worse with our "standard" formats

**Comment by diekhans** [comment]
Note that efo.obo starts with :
   format-version: 1.2

so it might be good to error on that rather than parse failures.

**Comment by althonos** [comment]
> Note that efo.obo starts with : format-version: 1.2 so it might be good to error on that rather than parse failures.

actually I can't do that because a lot of 1.4-compliant files are still exported with 1.2 as their format version for compatibility purposes, so I would potentially exclude valid files such as `go.obo`...

**Comment by mellybelly** [comment]
have you looked at ODK/ROBOT tools?

**Comment by althonos** [comment]
@mellybelly : the ODK embeds [`fastobo-validator`](https://github.com/fastobo/fastobo-validator) since INCATools/ontology-development-kit#215 so any OBO file generated by the ODK since then is actually compatible with format version 1.4

**Comment by diekhans** [comment]
All of the EBI ontologies I have look at are OBO 1.2, so pronto really shouldn't be used with their OBO format file.  OWL seems to work ok, except for UBERON

**Comment by althonos** [comment]
@diekhans : I know that for instance the [PSI-MI](https://www.ebi.ac.uk/ols/ontologies/mi) and [PSI-MS](https://www.ebi.ac.uk/ols/ontologies/ms) ontologies are compatible.

Basically, I would advise using the OBO file if it parses successfully, and fall back to the OWL otherwise, since `pronto` is probably working better with the OBO language design.
