### ISSUE TITLE
Python 3.8 on MacOS

### ISSUE THREAD

**Issue by mpreusse** [althonos/pronto#74]
Pronto uses nanoset (which is implemented in Rust). There is no pre-compiled version available for Python 3.8 on MacOS.

Would be helpful to note this dependency issue. To install with Python 3.8 on MacOS you need the rust toolchain.

**Comment by althonos** [comment]
Actually `nanoset` is optional, but since I got `fastobo` to compile with Python 3.8 on Mac OSX I should be able to do the same with `nanoset`. Can you open an issue [there](https://github.com/althonos/nanoset.py) as well ?

**Comment by mpreusse** [comment]
I opened an issue in the nanoset repo. 

When you `pip install pronto` pip tries to install nanoset. There is this `pip install packacke[optional]` syntax but I don't know how to build that :)

**Comment by althonos** [comment]
I'm aware of that syntax and how to use it, but then it will result in most people not installing `nanoset` even when they could. The reason i'm so insistent on using it is because it really shrinks the memory used by `pronto` (I designed it for that exact usecase), and without it your computer RAM is likely to melt when loading some large ontologies (like ChEBI or NCBITaxon).

But the issue should be fixed now, `nanoset v0.1.4` has wheels for Python 3.8 as well. Thanks for your feedback!
