### ISSUE TITLE
What to use instead of `rchildren` and `rparents`?

### ISSUE THREAD

**Issue by swartchris8** [althonos/pronto#81]
I have been using `0.* pronto` for a while and recently decided it might be better to migrate to a more up to date version.
In my code I heavily rely on rchildren and rparents to get all children and all parents how can I do this in `2.* pronto`?

**Comment by althonos** [comment]
Hi @swartchris8 ,

The new version is a bit better when it comes to ontology semantics, so now you should use `Term.subclasses` and `Term.superclasses` to query the same information. 

Since all terms/classes are also superclasses and subclasses of themselves (according to the RDF semantics of the `subClassOf` relationship), these methods will always yield the item itself as the first element of the iteration. To disable this (because it can get you in infinte loops if you're exploring stuff transitively), you can disable it with `with_self=False`.

Also, these methods now return an iterator, but if you want a set like before, you can simply chain a call to the `to_set` method. (Doing so instead of collecting with `set` grants you a `TermSet`, which uses lower memory and typechecks its content to be `Term` objects). 

```
>>> ms = pronto.Ontology.from_obo_library("ms.obo")
>>> ms['MS:1000495'].subclasses().to_set()
TermSet({Term('MS:1000204', name='Voyager-DE STR'), Term('MS:1000203', name='Voyager-DE PRO'), Term('MS:1000140', name='4700 Proteomics Analyzer'), Term('MS:1000495', name='Applied Biosystems instrument model'), Term('MS:1000658', name='4800 Proteomics Analyzer')})
>>> ms['MS:1000495'].subclasses(with_self=False).to_set()
TermSet({Term('MS:1000140', name='4700 Proteomics Analyzer'), Term('MS:1000203', name='Voyager-DE PRO'), Term('MS:1000204', name='Voyager-DE STR'), Term('MS:1000658', name='4800 Proteomics Analyzer')})
```

**Comment by swartchris8** [comment]
Thanks for the super helpful & detailed answer Althonos!

**Comment by althonos** [comment]
@swartchris8 : I have added this as a new section in the documentation (https://pronto.readthedocs.io/en/latest/updating.html). Feel free to contribute if anything else emerged while updating from a pre-`v1` version !
