### ISSUE TITLE
Adding a relationship between two terms

### ISSUE THREAD

**Issue by neobernad** [althonos/pronto#84]
Hi,

According to the docs I can see how I could create a relationship, however I do not manage to link two terms with a relationship. I would like to achieve something like:

```python
ms: Ontology = pronto.Ontology.from_obo_library("ms.obo")
rel_is_a: Relationship = ms.get_relationship("is_a")
ms['MS:1000031'].relationships.set(rel_is_a, ms['MS:1001792'])
```
Is this possible somehow?

Thanks,
José Antonio

**Comment by althonos** [comment]
Hi @neobernad 

currently there's no recommended way of doing it, mostly because I haven't taken the time to write a custom mapping class for the `Term.relationship` attribute that would perform a validation step on its arguments. Because of this, I use `frozendicts` for the time being, which you can't edit.  

Note that `is_a` is not considered as a normal relationship by the way: OBO relationships are semantically equivalent to OWL AnnotationProperty or ObjectProperty, while `is_a` is actually the `subClassOf` defined in the RDF schema. It is being exposed as a relationship for convenience with OBO, but actually it's handled differently.

I'm currently refactoring some parts of the parser interface, but I'll try to see what I can do before the next release.

**Comment by althonos** [comment]
However, if for the time being you **really really** need that feature, you can probably achieve that by fondling with pronto's internals (this is not guaranteed to work in the next versions but should at least work now.

## Subclasses

```python
ont: Ontology = pronto.Ontology()
ont.create_term("ONT:001")
ont.create_term("ONT:002")

ont._inheritance["ONT:001"].sub.add("ONT:002")   # register ONT:002 as a subclass of ONT:001
ont._inheritance["ONT:002"].sup.add("ONT:001")   # register ONT:001 as a superclass of ONT:002
````
Note that you must do both, otherwise [`Term.subclasses`](https://pronto.readthedocs.io/en/stable/api/pronto.Term.html#pronto.Term.subclasses) or [`Term.superclasses`](https://pronto.readthedocs.io/en/stable/api/pronto.Term.html#pronto.Term.superclasses) is bound to break.

## Relationships

```python
ont: Ontology = pronto.Ontology()
ont.create_term("ONT:001")
ont.create_term("ONT:002")
ont.create_relationship("better_than")

ont["ONT:002"]._data().relationships['better_than'] = {"ONT:001"}
```

Same, if you want to be semantically coherent, you'd need to take into account whether the relation is symmetric etc.

**Comment by neobernad** [comment]
Hi @althonos!

Thanks for the solution and your quick response, it worked for me, I really needed to establish the relationships.

**Comment by althonos** [comment]
Hi @neobernad ,

`v2.2.0` was released, and I changed the way to manage subclasses and superclasses. `is_a` relationship is soft-deprecated, and adding new subclasses to a term is done with the `subclasses` method:

```
ont: Ontology = pronto.Ontology()
t1 = ont.create_term("ONT:001")
t2 = ont.create_term("ONT:002")

t1.superclasses().add(t2)     # these two lines are equivalent,
t2.subclasses().add(t1)        # only call one of them.
```

For relationships, the snippet I wrote in the previous answer is the recommended way for now.

**Comment by neobernad** [comment]
Hello @althonos,

Thank you so much, this is really helpful. I will do it this way now!
