### ISSUE TITLE
Differences when parsing OBO and OWL files from OboFoundry

### ISSUE THREAD

**Issue by mpreusse** [althonos/pronto#88]
I tried using pronto to parse GO and other ontologies from OboFoundry.

When parsing OBO files, I can get relationships between terms with the `.relationships` property of the `Term` object. However, when parsing the same ontology from the OWL file, the `.relationships` property of the `Term` objects is empty.

Here is a minimal example with the (small) FAO ontology. It contains `part_of` relationships which are properly parsed from the OBO but not from the OWL file. The relationships do exist in the OWL file.

```
import pronto

# load fao from OWL and OBO file
fao_owl = pronto.Ontology.from_obo_library('fao.owl')
fao_obo = pronto.Ontology.from_obo_library('fao.obo')

# iterate terms loaded from OWL and print relationships
for term in fao_owl.terms():
    if term.relationships:
        print("from OWL", term.relationships)

# iterate terms loaded from OWL and print relationships
for term in fao_obo.terms():
    if term.relationships:
        print("from OBO", term.relationships)
```

Is this an issue of OBO to OWL mapping in general or a bug in the OWL parser?

More general question: How can I access the relationships from an OWL file?

**Comment by althonos** [comment]
Hi @mpreusse ,

The OWL parser in here is really provisional, and it will be ultimately replaced by a parser that works at the syntactical level and that translates from whatever OWL dialect to OBO directly. Since the library I was using didn't support OWL/XML yet, which is the widespread syntax for OWL files, I wrote a parser at the Python level, but it's still missing some features.

The relationships *in themselves* are extracted properly:
```python
>>> list(fao_owl.relationships())
[Relationship('part_of', name='part of'), Relationship('only_in_taxon', name='only in taxon'), Relationship('develops_from', name='develops from')]
```
But since in OWL, relationships are translated using `owl:Axiom`, I basically need to write a lot of extra code to get them working. It's planned, but I didn't have a lot of time to do this because of my PhD project.

As a rule a thumb, I'd always recommend to use the OBO file if both OBO and OWL are available for an ontology, given this library was originally (like 4 years ago) written with OBO in mind.

**Comment by althonos** [comment]
I added some relationship extraction capabilities to the RDF/XML parser: not all relationships are supported (like described in the [OBO to OWL semantic mappings](http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.3)), but the basic ones should be in `v2.2.2`.

**Comment by mpreusse** [comment]
Thanks for the update! I fully understand the time constraints.

It's good to know that I should focus on OBO. A common interface for OBO and OWL sounds very attractive though.
