### ISSUE TITLE
Could not find a parser to parse

### ISSUE THREAD

**Issue by oncolytics** [althonos/pronto#92]
Hello! Thanks for the very useful Ontology tool, but I bumped into an issue while downloading an rdf file.

**Example**
`uniprot_rdf = pronto.Ontology("https://ftp.expasy.org/databases/uniprot/current_release/rdf/taxonomy.rdf.xz")`

**Log**
```python
/python3.7/site-packages/pronto/parsers/base.py:47: UnicodeWarning: unsound encoding, assuming utf-8 (88% confidence)
  return Ontology(url, max(import_depth-1, -1), timeout)
Traceback (most recent call last):
  File "dump.py", line 4, in <module>
    uniprot_rdf = pronto.Ontology("https://ftp.expasy.org/databases/uniprot/current_release/rdf/taxonomy.rdf.xz")
  File "/python3.7/site-packages/pronto/ontology.py", line 171, in __init__
    cls(self).parse_from(_handle)
  File "/python3.7/site-packages/pronto/parsers/rdfxml.py", line 105, in parse_from
    threads=threads,
  File "/python3.7/site-packages/pronto/parsers/base.py", line 68, in process_imports
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/python3.7/site-packages/pronto/parsers/base.py", line 68, in <lambda>
    return dict(pool.map(lambda i: (i, process(i)), imports))
  File "/python3.7/site-packages/pronto/parsers/base.py", line 47, in process_import
    return Ontology(url, max(import_depth-1, -1), timeout)
  File "/python3.7/site-packages/pronto/ontology.py", line 174, in __init__
    raise ValueError(f"could not find a parser to parse {handle!r}")
ValueError: could not find a parser to parse 'http://purl.uniprot.org/core/'
```

I'm currently using the latest pronto version 2.2.3

Do you know what exactly is going on here? Uniprot only provides this rdf file (no obo file present on their ftp). Any workaround?

Thanks in advance!

**Comment by althonos** [comment]
Hi @oncolytics, two issues here: 

1. **on the purely technical side:** `pronto` is not aware of the LZMA (`.xz`) compression, so you need to decompress it yourself. This can be done by explicitly passing a file-like object to the `Ontology` constructor instead of a path, but then you need to handle the download and decompression yourself (which can be done with `urllib.request` and `lzma` from the standard library)
   ```python
   import urllib.request
   import lzma
   import pronto

   url = "https://ftp.expasy.org/databases/uniprot/current_release/rdf/taxonomy.rdf.xz"
   with urllib.request.urlopen(url) as res:
      taxonomy = pronto.Ontology(lzma.open(res))
   ```

2. **on the semantic side:** the file you're trying to download is a pure RDF/XML so it seems, not an OWL ontology, and the file does not declare any `owl:Class`, but only `rdf:Description` entities. So even if you manage to parse it with the first method, it is very likely to give you an `Ontology` empty of any term at the end.
